#include <stdio.h>
#include <stdlib.h>

int main()
{
    printf("Hello world!\n");
    return 0;
}

/*
MOVIMIENTOS TXT (ARCHIVO)
FECHA HORA NRO_CTA/COD-SUC TIPO_MOV MONTO
AÑO/M/DIA H:M:S 12345/AX47 (E/D) 10 DIGITOS Y 2 DECIMALES PARA EL MONTO

ORDENADO POR NRO_CTA COD-SUC FECHA HORA EN ESE ORDEN

DEL ARCHIVO DE MOVIMIENTOS QUIERO GENERAR DOS ARCHIVOS BINARIOS CON LA MISMA ESTRUCTURA , ARCH 1 MOVIMIENTOS DE DINERO CON MAS DE 10 MILLONES
ARCH 2 MOVIMIENTOS DE DINERO CON MENOS DE 10 MILLONES

ACUMULATIVO

1 REGISTRO POR CUENTA SUC, LA FECHA Y LA HORA SON LAS DEL ULTIMO MOV, NO HAY TIPO DE MOVIMIENTO, EL MONTO VA A SER EL ACUMULADO
APARECERAN EN EL MISMO ORDEN QUE EN EL ARCHIVO ORIGINAL DE MOVIMIENTOS.TXT

*/
